name: Trigger on demand Kubernetes Deployment workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy on"
        required: true
      release_tag:
        description: "The release tag"
        required: true
jobs:
  vg-deploy:
    uses: virusgeeks/.github/.github/workflows/vg-deploy-template.yml@master
    with:
      release_tag: ${{ github.event.inputs.release_tag }}
      environment: ${{ github.event.inputs.environment }}
    secrets:
      VG_NODE_TOKEN: ${{ secrets.VG_NODE_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEPLOY_ARN: ${{ secrets.AWS_DEPLOY_ARN }}
